version: '3'
services:

  db:
    container_name: db-mysql
    image: mysql:8
    environment:
#      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=app
    volumes:
      - db_project:/var/lib/mysql
  app:
    container_name: app-go
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db_project:
