// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "crud_api/entities"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function with given fields: body, ID
func (_m *Repository) Activate(body entities.Activate, ID string) (*entities.Activate, error) {
	ret := _m.Called(body, ID)

	var r0 *entities.Activate
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Activate, string) (*entities.Activate, error)); ok {
		return rf(body, ID)
	}
	if rf, ok := ret.Get(0).(func(entities.Activate, string) *entities.Activate); ok {
		r0 = rf(body, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Activate)
		}
	}

	if rf, ok := ret.Get(1).(func(entities.Activate, string) error); ok {
		r1 = rf(body, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type Repository_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - body entities.Activate
//   - ID string
func (_e *Repository_Expecter) Activate(body interface{}, ID interface{}) *Repository_Activate_Call {
	return &Repository_Activate_Call{Call: _e.mock.On("Activate", body, ID)}
}

func (_c *Repository_Activate_Call) Run(run func(body entities.Activate, ID string)) *Repository_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.Activate), args[1].(string))
	})
	return _c
}

func (_c *Repository_Activate_Call) Return(_a0 *entities.Activate, _a1 error) *Repository_Activate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Activate_Call) RunAndReturn(run func(entities.Activate, string) (*entities.Activate, error)) *Repository_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// Approval provides a mock function with given fields: body, ID
func (_m *Repository) Approval(body entities.Approval, ID string) (*entities.Approval, error) {
	ret := _m.Called(body, ID)

	var r0 *entities.Approval
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Approval, string) (*entities.Approval, error)); ok {
		return rf(body, ID)
	}
	if rf, ok := ret.Get(0).(func(entities.Approval, string) *entities.Approval); ok {
		r0 = rf(body, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Approval)
		}
	}

	if rf, ok := ret.Get(1).(func(entities.Approval, string) error); ok {
		r1 = rf(body, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Approval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Approval'
type Repository_Approval_Call struct {
	*mock.Call
}

// Approval is a helper method to define mock.On call
//   - body entities.Approval
//   - ID string
func (_e *Repository_Expecter) Approval(body interface{}, ID interface{}) *Repository_Approval_Call {
	return &Repository_Approval_Call{Call: _e.mock.On("Approval", body, ID)}
}

func (_c *Repository_Approval_Call) Run(run func(body entities.Approval, ID string)) *Repository_Approval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.Approval), args[1].(string))
	})
	return _c
}

func (_c *Repository_Approval_Call) Return(_a0 *entities.Approval, _a1 error) *Repository_Approval_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Approval_Call) RunAndReturn(run func(entities.Approval, string) (*entities.Approval, error)) *Repository_Approval_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function with given fields: ID
func (_m *Repository) DeleteByID(ID string) (*entities.Actors, error) {
	ret := _m.Called(ID)

	var r0 *entities.Actors
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Actors, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Actors); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Actors)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type Repository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ID string
func (_e *Repository_Expecter) DeleteByID(ID interface{}) *Repository_DeleteByID_Call {
	return &Repository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ID)}
}

func (_c *Repository_DeleteByID_Call) Run(run func(ID string)) *Repository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_DeleteByID_Call) Return(_a0 *entities.Actors, _a1 error) *Repository_DeleteByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_DeleteByID_Call) RunAndReturn(run func(string) (*entities.Actors, error)) *Repository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ID
func (_m *Repository) FindByID(ID string) ([]entities.Actors, error) {
	ret := _m.Called(ID)

	var r0 []entities.Actors
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entities.Actors, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(string) []entities.Actors); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Actors)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ID string
func (_e *Repository_Expecter) FindByID(ID interface{}) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", ID)}
}

func (_c *Repository_FindByID_Call) Run(run func(ID string)) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(_a0 []entities.Actors, _a1 error) *Repository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(string) ([]entities.Actors, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() ([]entities.Actors, error) {
	ret := _m.Called()

	var r0 []entities.Actors
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.Actors, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.Actors); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Actors)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type Repository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *Repository_Expecter) GetAll() *Repository_GetAll_Call {
	return &Repository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *Repository_GetAll_Call) Run(run func()) *Repository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_GetAll_Call) Return(_a0 []entities.Actors, _a1 error) *Repository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetAll_Call) RunAndReturn(run func() ([]entities.Actors, error)) *Repository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: username, password
func (_m *Repository) Login(username string, password string) (*entities.Actors, error) {
	ret := _m.Called(username, password)

	var r0 *entities.Actors
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*entities.Actors, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *entities.Actors); ok {
		r0 = rf(username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Actors)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type Repository_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *Repository_Expecter) Login(username interface{}, password interface{}) *Repository_Login_Call {
	return &Repository_Login_Call{Call: _e.mock.On("Login", username, password)}
}

func (_c *Repository_Login_Call) Run(run func(username string, password string)) *Repository_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Repository_Login_Call) Return(_a0 *entities.Actors, _a1 error) *Repository_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Login_Call) RunAndReturn(run func(string, string) (*entities.Actors, error)) *Repository_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: actors
func (_m *Repository) Save(actors *entities.Actors) error {
	ret := _m.Called(actors)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Actors) error); ok {
		r0 = rf(actors)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - actors *entities.Actors
func (_e *Repository_Expecter) Save(actors interface{}) *Repository_Save_Call {
	return &Repository_Save_Call{Call: _e.mock.On("Save", actors)}
}

func (_c *Repository_Save_Call) Run(run func(actors *entities.Actors)) *Repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Actors))
	})
	return _c
}

func (_c *Repository_Save_Call) Return(_a0 error) *Repository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Save_Call) RunAndReturn(run func(*entities.Actors) error) *Repository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function with given fields: body, ID
func (_m *Repository) UpdateByID(body entities.Actors, ID string) (*entities.Actors, error) {
	ret := _m.Called(body, ID)

	var r0 *entities.Actors
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Actors, string) (*entities.Actors, error)); ok {
		return rf(body, ID)
	}
	if rf, ok := ret.Get(0).(func(entities.Actors, string) *entities.Actors); ok {
		r0 = rf(body, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Actors)
		}
	}

	if rf, ok := ret.Get(1).(func(entities.Actors, string) error); ok {
		r1 = rf(body, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type Repository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - body entities.Actors
//   - ID string
func (_e *Repository_Expecter) UpdateByID(body interface{}, ID interface{}) *Repository_UpdateByID_Call {
	return &Repository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", body, ID)}
}

func (_c *Repository_UpdateByID_Call) Run(run func(body entities.Actors, ID string)) *Repository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entities.Actors), args[1].(string))
	})
	return _c
}

func (_c *Repository_UpdateByID_Call) Return(_a0 *entities.Actors, _a1 error) *Repository_UpdateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_UpdateByID_Call) RunAndReturn(run func(entities.Actors, string) (*entities.Actors, error)) *Repository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
